# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hand.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1290, 821)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 10, 631, 121))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.web_font = FontComboBox(Form)
        self.web_font.setGeometry(QtCore.QRect(120, 240, 321, 22))
        self.web_font.setObjectName("web_font")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 72, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.font_color = QtWidgets.QPushButton(Form)
        self.font_color.setGeometry(QtCore.QRect(120, 320, 321, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.font_color.setFont(font)
        self.font_color.setObjectName("font_color")
        self.border_color = QtWidgets.QPushButton(Form)
        self.border_color.setGeometry(QtCore.QRect(120, 400, 321, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.border_color.setFont(font)
        self.border_color.setObjectName("border_color")
        self.sure = QtWidgets.QPushButton(Form)
        self.sure.setGeometry(QtCore.QRect(120, 470, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sure.setFont(font)
        self.sure.setObjectName("sure")
        self.input_text = QtWidgets.QLineEdit(Form)
        self.input_text.setGeometry(QtCore.QRect(140, 160, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_text.setFont(font)
        self.input_text.setObjectName("input_text")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(250, 470, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(450, 120, 801, 501))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "手写签名"))
        self.label_2.setText(_translate("Form", "字体："))
        self.font_color.setText(_translate("Form", "字体颜色"))
        self.border_color.setText(_translate("Form", "字体边框"))
        self.sure.setText(_translate("Form", "确定"))
        self.input_text.setPlaceholderText(_translate("Form", "输入文字："))
        self.save.setText(_translate("Form", "保存"))
from control.fontcombobox import FontComboBox
