# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spin.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 417)
        self.width_spin = QtWidgets.QSpinBox(Form)
        self.width_spin.setGeometry(QtCore.QRect(360, 50, 161, 22))
        self.width_spin.setMaximum(400)
        self.width_spin.setObjectName("width_spin")
        self.test_btn = QtWidgets.QPushButton(Form)
        self.test_btn.setGeometry(QtCore.QRect(300, 340, 100, 41))
        self.test_btn.setStyleSheet("")
        self.test_btn.setObjectName("test_btn")
        self.height_spin = QtWidgets.QSpinBox(Form)
        self.height_spin.setGeometry(QtCore.QRect(360, 100, 161, 22))
        self.height_spin.setMaximum(400)
        self.height_spin.setObjectName("height_spin")
        self.r_spin = QtWidgets.QSpinBox(Form)
        self.r_spin.setGeometry(QtCore.QRect(370, 160, 161, 22))
        self.r_spin.setMaximum(200)
        self.r_spin.setObjectName("r_spin")
        self.b_spin = QtWidgets.QSpinBox(Form)
        self.b_spin.setGeometry(QtCore.QRect(370, 240, 161, 22))
        self.b_spin.setObjectName("b_spin")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 60, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 170, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(260, 240, 72, 15))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.test_btn.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "按钮的宽度"))
        self.label_2.setText(_translate("Form", "按钮的高度"))
        self.label_3.setText(_translate("Form", "  半径"))
        self.label_4.setText(_translate("Form", "边框"))
