# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 390)
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setGeometry(QtCore.QRect(110, 30, 93, 28))
        self.ok.setObjectName("ok")
        self.yellow = QtWidgets.QRadioButton(Form)
        self.yellow.setGeometry(QtCore.QRect(350, 200, 115, 19))
        self.yellow.setObjectName("yellow")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(80, 90, 381, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.bold = QtWidgets.QCheckBox(self.groupBox)
        self.bold.setGeometry(QtCore.QRect(0, 30, 91, 19))
        self.bold.setObjectName("bold")
        self.underline = QtWidgets.QCheckBox(self.groupBox)
        self.underline.setGeometry(QtCore.QRect(250, 30, 91, 19))
        self.underline.setObjectName("underline")
        self.italic = QtWidgets.QCheckBox(self.groupBox)
        self.italic.setGeometry(QtCore.QRect(130, 30, 91, 19))
        self.italic.setObjectName("italic")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 280, 261, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.red = QtWidgets.QRadioButton(Form)
        self.red.setGeometry(QtCore.QRect(90, 200, 115, 19))
        self.red.setObjectName("red")
        self.blue = QtWidgets.QRadioButton(Form)
        self.blue.setGeometry(QtCore.QRect(240, 200, 115, 19))
        self.blue.setObjectName("blue")
        self.loser = QtWidgets.QPushButton(Form)
        self.loser.setGeometry(QtCore.QRect(290, 30, 93, 28))
        self.loser.setObjectName("loser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ok.setText(_translate("Form", "确定"))
        self.yellow.setText(_translate("Form", "黄"))
        self.bold.setText(_translate("Form", "粗体"))
        self.underline.setText(_translate("Form", "下划线"))
        self.italic.setText(_translate("Form", "斜体"))
        self.label.setText(_translate("Form", "测试标签"))
        self.red.setText(_translate("Form", "红"))
        self.blue.setText(_translate("Form", "蓝"))
        self.loser.setText(_translate("Form", "取消"))
