# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tables.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1221, 809)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 160, 991, 571))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.loser = QtWidgets.QPushButton(Form)
        self.loser.setGeometry(QtCore.QRect(180, 20, 93, 28))
        self.loser.setObjectName("loser")
        self.read = QtWidgets.QPushButton(Form)
        self.read.setGeometry(QtCore.QRect(50, 20, 93, 28))
        self.read.setObjectName("read")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(320, 20, 93, 28))
        self.add.setObjectName("add")
        self.delete_btn = QtWidgets.QPushButton(Form)
        self.delete_btn.setGeometry(QtCore.QRect(470, 20, 93, 28))
        self.delete_btn.setObjectName("delete_btn")
        self.alter = QtWidgets.QPushButton(Form)
        self.alter.setGeometry(QtCore.QRect(620, 20, 93, 28))
        self.alter.setObjectName("alter")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(780, 100, 93, 28))
        self.save.setObjectName("save")
        self.query = QtWidgets.QPushButton(Form)
        self.query.setGeometry(QtCore.QRect(60, 90, 93, 28))
        self.query.setObjectName("query")
        self.word = QtWidgets.QComboBox(Form)
        self.word.setGeometry(QtCore.QRect(190, 100, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.word.setFont(font)
        self.word.setObjectName("word")
        self.symbol = QtWidgets.QComboBox(Form)
        self.symbol.setGeometry(QtCore.QRect(380, 100, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.symbol.setFont(font)
        self.symbol.setObjectName("symbol")
        self.symbol.addItem("")
        self.symbol.addItem("")
        self.symbol.addItem("")
        self.symbol.addItem("")
        self.word_content = QtWidgets.QLineEdit(Form)
        self.word_content.setGeometry(QtCore.QRect(580, 100, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.word_content.setFont(font)
        self.word_content.setObjectName("word_content")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loser.setText(_translate("Form", "退出"))
        self.read.setText(_translate("Form", "读取"))
        self.add.setText(_translate("Form", "增"))
        self.delete_btn.setText(_translate("Form", "删"))
        self.alter.setText(_translate("Form", "改"))
        self.save.setText(_translate("Form", "保存"))
        self.query.setText(_translate("Form", "查询"))
        self.symbol.setItemText(0, _translate("Form", ">"))
        self.symbol.setItemText(1, _translate("Form", "<"))
        self.symbol.setItemText(2, _translate("Form", "="))
        self.symbol.setItemText(3, _translate("Form", "like"))
